name: "COURSIT TEST COMMAND"
author: "COURSIT"
description: "Autograder to run any command and save stdout."
inputs:
  test-name:
    description: "The unique identifier for the test."
    required: true
  setup-command:
    description: "Command to execute prior to the test, typically for environment setup or dependency installation."
    required: false
  command:
    description: "Primary command to run for the test. A zero exit code signifies a successful test."
    required: true
  timeout:
    description: "Duration (in minutes) before the test is terminated. Defaults to 10 minutes with a maximum limit of 6 hours."
    default: "10"
    required: false
outputs:
  result:
    description: "Outputs the result of the grader, indicating the success or failure of the test."
runs:
  using: 'node20'
  main: 'dist/main.js'

